name: HLint

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

      path:
        required: true
        type: string

jobs:
  hlint:
    name: Run HLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: haskell/actions/hlint-setup@v1.2.9
        with:
          version: ${{ inputs.version }}

      - uses: haskell/actions/hlint-run@v1.2.9
        with:
          path: ${{ inputs.path }}
        fail-on: warning
