name: Haskell

on:
  workflow_call:
    inputs:
      ghc-versions:
        type: string
        default: latest
        required: false

      cabal-versions:
        type: string
        default: latest
        required: false

      unstable-ghc-versions:
        type: string
        default: ""
        required: false

jobs:
  process-inputs:
    name: "Process inputs"
    runs-on: ubuntu-latest
    outputs:
      ghc-versions: ${{ steps.main.outputs.ghc-versions }}
      unstable-ghc-versions: ${{ steps.main.outputs.unstable-ghc-versions }}
      cabal-versions: ${{ steps.main.outputs.cabal-versions }}
    steps:
      - id: main
        run: |
          ghc_versions_spaced=$(echo "${{ inputs.ghc-versions }}" | sort -u | tr '[:space:]' ' ' | xargs)
          ghc_versions_inner=$(echo '"'${ghc_versions_spaced// /'", "'}'"')
          echo "::set-output name=ghc-versions::[$ghc_versions_inner]"

          unstable_ghc_versions_spaced=$(echo "${{ inputs.unstable-ghc-versions }}" | sort -u | tr '[:space:]' ' ' | xargs)
          unstable_ghc_versions_inner=$(echo '"'${unstable_ghc_versions_spaced// /'", "'}'"')
          echo "::set-output name=unstable-ghc-versions::[$unstable_ghc_versions_inner]"

          cabal_versions_spaced=$(echo "${{ inputs.cabal-versions }}" | sort -u | tr '[:space:]' ' ' | xargs)
          cabal_versions_inner=$(echo '"'${cabal_versions_spaced// /'", "'}'"')
          echo "::set-output name=cabal-versions::[$cabal_versions_inner]"

  build-and-test:
    name: "Build and Test"
    needs: process-inputs
    strategy:
      matrix:
        ghc-version: ${{ fromJSON(needs.process-inputs.outputs.ghc-versions) }}
        cabal-version: ${{ fromJSON(needs.process-inputs.outputs.cabal-versions) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cabal/packages
            ~/.cabal/store
            dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc-version }}

      - uses: haskell/actions/setup@v1.2.9
        with:
          ghc-version: ${{ matrix.ghc-version }}
          cabal-version: ${{ matrix.cabal-version }}

      - run: cabal configure --disable-documentation --enable-tests --disable-optimization

      - run: cabal build --dependencies-only all

      - run: cabal build all

      - run: cabal test all

  build-and-test-unstable:
    name: "Build and Test"
    needs: process-inputs
    strategy:
      matrix:
        ghc-version: ${{ fromJSON(needs.process-inputs.outputs.unstable-ghc-versions) }}
        cabal-version: ${{ fromJSON(needs.process-inputs.outputs.cabal-versions) }}
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cabal/packages
            ~/.cabal/store
            dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc-version }}

      - uses: haskell/actions/setup@v1.2.9
        with:
          ghc-version: ${{ matrix.ghc-version }}
          cabal-version: ${{ matrix.cabal-version }}

      - run: cabal configure --disable-documentation --enable-tests --disable-optimization

      - run: cabal build --dependencies-only all

      - run: cabal build all

      - run: cabal test all
