name: HLint

on:
  workflow_call:
    inputs:
      version:
        required: false
        default: "3.3.6"
        type: string

      path:
        required: true
        type: string

jobs:
  hlint:
    name: Run HLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Set up HLint
        uses: haskell/actions/hlint-setup@v1.2.9
        with:
          version: ${{ inputs.version }}

      - name: Run HLint
        uses: haskell/actions/hlint-run@v1.2.9
        with:
          path: ${{ inputs.path }}
          fail-on: warning
